name: Lint check

on: [push, pull_request]

jobs:
  lint-clang-format:
    name: Lint with clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check code with clang-format
        uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: "14"
